FROM nginx

RUN apt-get update -qq && apt-get -y install apache2-utils

ENV RAILS_ROOT /var/www/rails_5_rc1_docker

WORKDIR $RAILS_ROOT

RUN mkdir log

COPY public public/

COPY config/containers/nginx.conf /tmp/rails_5_rc1_docker.nginx

# substitute variable references in the Nginx config template for real values from the environment
# put the final config in its place
RUN envsubst '$RAILS_ROOT' < /tmp/rails_5_rc1_docker.nginx > /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
